### ISSUE TITLE
v2.022.08 breaks Certificate Check

### ISSUE THREAD

**Issue by amks1** [kobotoolbox/kobo-install#186]
**Description**

In the new version (I tested with tag `2.022.08`) where the question to fetch the certificates from LetsEncrypt appears after the containers are built instead of before I noticed the following issues:

1. If I choose "N" (don't re-fetch certificates) for a previously installed domain, all containers come up but the website is unreachable. I have to always fetch certificates in order to continue. Because I was doing tests I kept hitting the LetsEncrypt limits and had to keep making new subdomains. Which brings me to the next point.
2. It always says that the certificates are present even if I enter a brand new subdomain name.

**Steps to Reproduce: Issue 1 above**
1. Run `run.py --setup` and install new certificates.
2. Run `run.py --setup` again, presumably with some changes. But don't install new certificates when asked.
3. Containers come up but website is unreachable.
4. Run `run.py --setup` again, with no other changes other than this time, choose "y" for the certificate.
5. Containers come up and website is working. 

**Steps to Reproduce: Issue 2 above**
1. Run `run.py --setup` and install new certificates.
2. Run `run.py --setup` again, with a different subdomain. 
3. At the time of certificate check, it says that the certificates are already present for this domain.

**Comment by noliveleger** [comment]
@amks1, 
Issue 1 was indeed a problem with `--setup` not bringing up the letsencrypt containers. 
For the latter, #233 should fix it but if all subdomains are changed. If you changed only one or two but not first one, the prompt will still appear. 
It's because of the way `certbot` generates folders. it only uses the first domain as the folder name. 
Because it is an edge case, it is easier to delete the folder entirely and let the init script recreate it entirely
