### ISSUE TITLE
Unable to configure https

### ISSUE THREAD

**Issue by manetrejo** [kobotoolbox/kobo-install#197]
I'm trying to install a Kobo server. 
I could end only one successful setup: HTTPS: Yes and Behind Proxy: No
Of course HTTPS is a must, so I also tried:
- HTTPS: Yes, Auto-install https: No On this server: Yes, Internal port: 8080
- HTTPS: Yes, Auto-install https: Yes 
- HTTPS: Yes, Auto-install https: No On this server: No, Internal port: 8080

Different errors are shown, sadness is everywhere.
I also tried in Digital Ocean and Amazon Lightsail and on Ubuntu 18.04 and 20.04.
Nothing had work.

Please, any idea?
I really will appreciate it.
Thanks!

**Comment by noliveleger** [comment]
Hi @manetrejo, 

> I could end only one successful setup: HTTPS: Yes and Behind Proxy: No

That's the trivial case and you don't use a HTTPS proxy yourself (like AWS load balancer with SSL certificate), that's the way to do it.

Otherwise, please open a thread on the community forum to get assistance. We use GH issues to track bugs and features.
As the disclaimer says when you open a new issue, we cannot provided support or guidance over here.

> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script
