### ISSUE TITLE
Maximum Media size

### ISSUE THREAD

**Issue by Kanchan112** [kobotoolbox/kobo-install#199]
**Description**
How can we increase the maximum limit size of uploading media in a deployed kobo server?

**Comment by noliveleger** [comment]
Hi @Kanchan112 , 

Is 100 MB not enough? Increasing this can bring some problems with slow client connections.
Have a look at `client_max_body_size 100M;` in nginx configurations. 

Otherwise, please open a thread on the community forum to get assistance. We use GH issues to track bugs and features.
As the disclaimer says when you open a new issue, we cannot provided support or guidance over here.

> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script
