### ISSUE TITLE
Unable to initiate kobotoolbox in an EC2 instance

### ISSUE THREAD

**Issue by karakostis** [kobotoolbox/kobo-install#20]
I am trying to install the kobotoolbox in a fresh EC2 instance of AWS. I follow the below steps:

1. apt-get update
2. apt-get upgrade
3.[ install docker ](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04)
4.[ install docker-composer ](https://docs.docker.com/compose/install/)
5. git clone https://github.com/kobotoolbox/kobo-install.git
6. sudo python3 run.py

The service is never initiated (attached screenshot) and in the log file I see the below error: 
![Screen Shot 2019-04-03 at 4 30 14 PM](https://user-images.githubusercontent.com/17905221/55487423-5a00d880-562e-11e9-952f-1053a408d949.png)

`ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.frontend.yml'`

**Comment by noliveleger** [comment]
@karakostis, it doesn't seem to have run the setup first? 
Can you try to force the setup and retry (`python3 run.py -s`)?
BTW, you should not need to use `sudo`.  If it's because `docker` doesn't start, you may want to follow these extra steps https://docs.docker.com/install/linux/linux-postinstall/

**Comment by jnm** [comment]
You might find this helpful:
https://community.kobotoolbox.org/t/kobo-install-on-a-fresh-ubuntu-18-04-lts-vps/3250

Please re-open this issue if you'd like to add further detail.
