### ISSUE TITLE
Running $kobo-install> python run.py --setup to update Public domain name

### ISSUE THREAD

**Issue by adam704a** [kobotoolbox/kobo-install#36]
Everything seems to be working (great job guys and gals on that), but when rerean the setup to change the public domain things got weird. I am still seeing the old domain reference in different places in  kf. This happens when I try to redeloy a form and when I go into Settings -> Media. I was just hoping to know what files I can update to fix this problem. Thanks.

**Comment by noliveleger** [comment]
@adam704a, old forms will refer to old domain name because it has been copied into the db with the form's meta data. 
You need to change it manually in the PostgreSQL and redis. 
You ask/search for some guidance on https://community.kobotoolbox.org/
I'm closing this issue because it's not related to `kobo-install`.
