### ISSUE TITLE
TypeError: must be char, not unicode: Python 2.7.5

### ISSUE THREAD

**Issue by dpadron** [kobotoolbox/kobo-install#41]
S.O. Centos 7
------------------------------------

Traceback (most recent call last):
  File "run.py", line 66, in <module>
    run()
  File "run.py", line 26, in run
    current_config = config.build()
  File "/opt/kobo-install/helpers/config.py", line 211, in build
    self.__detect_network()
  File "/opt/kobo-install/helpers/config.py", line 404, in __detect_network
    interfaces = Network.get_local_interfaces()
  File "/opt/kobo-install/helpers/network.py", line 55, in get_local_interfaces
    names = array.array('B', MAX_BYTES * FILL_CHAR)
TypeError: must be char, not unicode

![error_kobo-install](https://user-images.githubusercontent.com/7094961/60008094-b98de380-9673-11e9-8852-2164c72e9d09.jpg)

**Comment by noliveleger** [comment]
@dpadron: Which version of python?

**Comment by dpadron** [comment]
Hi noliveleger 

Centos 7
Python 2.7.5

**Comment by noliveleger** [comment]
Can you try with a latest version of python 2.7 or python 3.4 and higher?

**Comment by dpadron** [comment]
regards
I have updated Python to 3.6 and the problem continues.
SW. Centos 7
Pythin 3.6

Someone who can guide me how to solve this problem.

If I select the option: 1) On your workstation, if it advances, but when I select option 2) On a server, the error is generated.

I need to change port 80 and 443, to be able to run Kobo-Tools
![error_kobo-tools](https://user-images.githubusercontent.com/7094961/60680283-f97e7300-9e8a-11e9-8196-66da7484c975.png)

**Comment by noliveleger** [comment]
@dpadron: Should you try `python3 run.py` to use python3.  
Otherwise you need to upgrade python 2.7 to latest minor patch. https://bugs.python.org/issue20014

**Comment by luisbauti92** [comment]
I have a same problem.
SO: CentOS 7
python: 3.6

```
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    run(force_setup=True)
  File "run.py", line 26, in run
    current_config = config.build()
  File "/home/development/kobo-install/helpers/config.py", line 206, in build
    self.__welcome()
  File "/home/development/kobo-install/helpers/config.py", line 1224, in __welcome
    CLI.colored_print("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557", CLI.COLOR_WARNING)
  File "/home/development/kobo-install/helpers/cli.py", line 46, in colored_print
    print(cls.colorize(message, color))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-69: ordinal not in range(128)
```

any idea?

**Comment by yonefx** [comment]
I have the same problem on CentOS7 as well

`╔═══════════════════════════════════════════════════════════════╗
║ Welcome to KoBoInstall!                                       ║
║                                                               ║
║ You are going to be asked some questions that will            ║
║ determine how to build the configuration of `KoBoToolBox`.    ║
║                                                               ║
║ Some questions already have default values (within brackets). ║
║ Just press `enter` to accept the default value or enter `-`   ║
║ to remove previously entered value.                           ║
║ Otherwise choose between choices or type your answer.         ║
╚═══════════════════════════════════════════════════════════════╝
Where do you want to install?
[/home/thammasin/kobo-docker]: 
Please confirm path [/home/thammasin/kobo-docker]
	1) Yes
	2) No
[1]: 
Do you want to see advanced options?
	1) Yes
	2) No
[2]: 1
What kind of installation do you need?
	1) On your workstation
	2) On a server
[2]: 1
Please choose which network interface you want to use?
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    run()
  File "run.py", line 26, in run
    current_config = config.build()
  File "/home/thammasin/kobo-install/helpers/config.py", line 211, in build
    self.__detect_network()
  File "/home/thammasin/kobo-install/helpers/config.py", line 404, in __detect_network
    interfaces = Network.get_local_interfaces()
  File "/home/thammasin/kobo-install/helpers/network.py", line 55, in get_local_interfaces
    names = array.array('B', MAX_BYTES * FILL_CHAR)
TypeError: must be char, not unicode
`
