### ISSUE TITLE
Need to raise Enketo's Text field character limit

### ISSUE THREAD

**Issue by ekansa** [kobotoolbox/kobo-install#44]
Hi,

I need to raise the character length limits in text fields from the default 2000 to something much bigger (see https://groups.google.com/forum/#!topic/enketo-users/5qYlmC7yxNc). 

I've been running Kobo from docker for field projects over the past 3 years now, and we never ran into the character length issue before. A few points:
(1) text character length seems like a really important config that it would great to specify in the kobo-install options perhaps a TODO on this?
(2) [SOLVED -- See below] I now have a working deployment from kobo-install, with people entering data now. I need to update this now without risking my current deployment.

Thanks in advance!

EDIT: I figured out where to edit the config in `/kobo-deployments/enketo_express/config.json` and I used the `python run.py --stop` and then `python run.py` command to stop and restart the docker containers. I still think it will be useful to make this important bit of configuration easier to edit. Thanks!

**Comment by noliveleger** [comment]
@ekansa, Thank you for you suggestion. If we add it to `kobo-install` setup,  we'll update this ticket.
FYI, don't run `run.py -s` again otherwise it will overwrite your changes in `/kobo-deployments/enketo_express/config.json`.
If you need to use `run.py -s`again. 
You can change the template in `kobo-install/templates/kobo-deployments/enketo_express/config.json.tpl`.

**Comment by noliveleger** [comment]
Limited has been increased with [this commit](https://github.com/kobotoolbox/kobo-install/commit/e450d53fa8f96d0cd3bb4018c4a43d7b2459f28a)
