### ISSUE TITLE
Is there any API that can be used to get data from the app so we can connect it to another app

### ISSUE THREAD

**Issue by FavourOyewumi7** [kobotoolbox/kobo-install#71]
**Description**
 

**Steps to Reproduce**

**Expected behavior**

**Desktop**

 - OS:  
 - Python Version: 
 - Docker Version: 
 - Docker Compose Version:
 
**Additional context**

**Comment by noliveleger** [comment]
Hi @FavourOyewumi7,

You should look at KPI API. (https://kf.yourdomain/api/v2/) .
You can still use `Rest Services` option within your form to resend data to external endpoint when it comes in. (Form / settings / Rest Services)
Please visit https://community.kobotoolbox.org/ to get more help.

I'm closing the issue because it's not related to `kobo-install`

**Comment by FavourOyewumi7** [comment]
Thanks

**Comment by noliveleger** [comment]
For reference, please have a look at this article http://support.kobotoolbox.org/en/articles/592398-api-and-rest-services
(cc @FavourOyewumi7 )
