### ISSUE TITLE
[two-databases] KPI data is not copied from KC to KPI when using default options.

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobo-install#79]
KPI database is created but empty.

**Comment by jnm** [comment]
In fact, not only does it not copy KPI data, but it creates a new, empty database for KoBoCAT! For example, after upgrading from `2.019.52-final-shared-database` to `two-databases`, I have three Postgres databases:
* `kobotoolbox` (has data for both KPI and KoBoCAT)
* `kobocat` (empty)
* `koboform` (empty)

**Comment by jnm** [comment]
`__questions_postgres()` only runs if the installer elects to see advanced options:
https://github.com/kobotoolbox/kobo-install/blob/97d53808e4c2f829e0789ffa946ae99b636255c3/helpers/config.py#L236-L240
and `__questions_postgres()` is the only place where we deal with changing `postgres_db` to `kpi_postgres_db` and `kc_postgres_db`:
https://github.com/kobotoolbox/kobo-install/blob/97d53808e4c2f829e0789ffa946ae99b636255c3/helpers/config.py#L872-L888

**Comment by noliveleger** [comment]
@jnm you are right and it should be fixed in #72.

**Comment by jnm** [comment]
Well, I have no idea how I didn't see this before :facepalm: 
![image](https://user-images.githubusercontent.com/2085013/79945383-a38bb380-843b-11ea-9689-c9e69995319c.png)

Thanks for pointing it out. I'll still advocate for my #83 because this (from #72) prevents downgrading, right? (by removing `postgres_db` from the configuration)
https://github.com/kobotoolbox/kobo-install/blob/ccce627c97653b7da15bb4edefa6c1ef758e5d30/helpers/config.py#L1552-L1555

Also, #72 is large and I am neck-deep in the release process for `two-databases`. I really want to finish that release and merge-to-master ASAP.
